### ISSUE TITLE
Unable to select ABL radio button on mobile device 

### ISSUE THREAD

**Issue by wtangent** [FABtotum/FAB-UI#19]
Configuration: sony experia z1 compact as currently with chrome browser 43.0.2357.93 and fabtotum running on firmware 1.0.008 and FABUI 0.91

Originally posted here:
http://forum.fabtotum.cc/showthread.php?2261-Unable-to-select-ABL-radio-button-on-mobile-device&p=14584#post14584

Issue: I can't select (the ABL) radio button(s) on touch sensitive screens. The option is shown after starting a print and all axis are homed.
Both selecting on my mobile device and through chrome:inspect on my laptop's touchscreen or touch-pad(mouse) didn't work.
Chrome:inspect shows it is labeled as input radio button, but somehow it isn't selectable. See print screen below for details.

When accessing FabUI on same laptop through a desktop browser directly(preferably chrome and IE, Firefox shows some strange behavior on radio buttons as well) there is no problem for touchscreen nor touch pad(mouse).

**Comment by christopherwit** [comment]
Hi just to let you know radio buttons on settings menu are not selectable as well.

**Comment by christopherwit** [comment]
Noticed today that selection boxes (squares with crosses inside) for items in an object(accessed through objectmanager) are applicable to the same problem.

**Comment by kriosmane** [comment]
Closed with version: 0.9497
