### ISSUE TITLE
Maintenance - Clean the extruder section is missing

### ISSUE THREAD

**Issue by bilderbuchi** [FABtotum/FAB-UI#20]
In the manual, page 10, under Maintenance - Nozzle blockage - Clean the extruder, this is printed:
> If the extruder is dirty or jammed
go to FAB UI/Settings/Clean
the extruder and follow
the instructions on-screen

The section `FAB UI/Settings/Clean the extruder` does not exist. Neither does `FAB UI/Maintenance/Clean the extruder`, which is where I think it is supposed to be (so that's maybe an error in the manual text).

FabUI is up to date, FAB UI beta v.0.9485.

**Comment by wtangent** [comment]
manual has been updated
