### ISSUE TITLE
support page FAQ error

### ISSUE THREAD

**Issue by koghe** [FABtotum/FAB-UI#22]
Hi all 
click on the support page FAQ give 

A PHP Error was encountered
Severity: Notice
Message: Undefined index: title
Filename: index/index.php
Line Number: 61

looking at 
/var/www/fabui/application/modules/support/views/index/index.php
/var/www/fabui/script/faq.php 
/var/www/temp/faq.json
all is correct but ther's no mysql table in the DB as i can see with phpmyadmin

edit: sorry just realized that faq are not in the db but is just parsing the json file
i'm learning how ui is developed :) 

cheers

**Comment by kriosmane** [comment]
Fixed on new version 0.9495

**Comment by koghe** [comment]
thanks! nice to know i was right :)
