### ISSUE TITLE
First time setup dialog - don't ask me anymore button doesn't have expected result

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/FAB-UI#24]
First time setup dialog keeps showing up on restart of fabtotum, after selecting "don't ask me anymore".

**Comment by kriosmane** [comment]
Hi, 
 "don't ask me anymore" is about the current session, so everytime you restart the fabtotum and you didn't complete the "first setup" wizard, it will appear again

**Comment by christopherwit** [comment]
Hi,

Thanks for getting back on this issue.
Yes I noticed. This is all well covered in the forum thread: http://forum.fabtotum.cc/showthread.php?2822-Software-and-Firmware-update-23-12-2015&p=16120#post16120

In my opinion the button NO should have affect to the Session(which as far as I understood is even page specific since the popup returns on navigating to a different menu item).
Don't ask me anymore should have the same effect as finishing the wizard and remove the WIZARD file, in order to close the warning for infinite time.

**Comment by kriosmane** [comment]
We agree with you, we'll introduce this behaviour in the next updates.
Thanks for your contribution

**Comment by christopherwit** [comment]
Hi Kriosmane,

Just to let you know that update fabui version 0.9496 made the don't show me anymore button persistent for the session.
If I do reopen my browser and navigate to the fabui the message still returns. In addition the WIZARD file remains.

**Comment by kriosmane** [comment]
Hi, 
the feature  will be available with the next update.

**Comment by kriosmane** [comment]
Issue closed on fabui version 0.9497
