### ISSUE TITLE
transfer_rate.sh contain ^M windows 

### ISSUE THREAD

**Issue by koghe** [FABtotum/FAB-UI#28]
the follow error generate a php error in the system info page

shell script must be converted to plain text to work,  apache error log show 

/var/www/fabui/script/transfer_rate.sh: 2: /var/www/fabui/script/transfer_rate.sh: ^M: not found
/var/www/fabui/script/transfer_rate.sh: 4: /var/www/fabui/script/transfer_rate.sh: ^M: not found
cat: /sys/class/net/eth0^M/statistics/rx_bytes: No such file or directory
cat: /sys/class/net/eth0^M/statistics/tx_bytes: No such file or directory
/var/www/fabui/script/transfer_rate.sh: 7: /var/www/fabui/script/transfer_rate.sh: ^M: not found
cat: /sys/class/net/eth0^M/statistics/rx_bytes: No such file or directory
cat: /sys/class/net/eth0^M/statistics/tx_bytes: No such file or directory
expr: non-integer argument
expr: non-integer argument

to solve 
cd /var/www/fabui/script
apt-get install dos2unix 
dos2unix transfer_rate.sh

only eth0 interface is queried that is only connected during first install or special cases
using wlan0 is better in general, you can query all interfaces and show results in 
fabui/application/modules/maintenance/views/systeminfo/widget.php line 75, 79 
add after sleep 1;

INTERFACE=wlan0

**Comment by wtangent** [comment]
@kriosmane said this is fixed in the next release.

**Comment by koghe** [comment]
Thanks @wtangent and @kriosmane this is a minor bug :+1:
