### ISSUE TITLE
wrong filament_diameter in slicer config? 

### ISSUE THREAD

**Issue by mgcrea** [FABtotum/FAB-UI#4]
In this slic3r config file: [set_1.ini](https://github.com/FABtotum/FAB-UI/blob/master/fabui/slic3r/configs/set_1.ini#L28)

there is:

`filament_diameter = 1.75`

shouldn't it be?

`filament_diameter = 3.0`

**Comment by wtangent** [comment]
Configs are now available here:
https://github.com/FABtotum/FAB_Configs

thanks for your feedback.
